language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements-testing.txt
  - python setup.py install
before_script:
  - cp -r test build/lib
script:
  - nosetests --where=build/lib
notifications:
  email: false
